package application;

import javafx.fxml.FXML;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.event.ActionEvent;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class MainFormController {
	@FXML
	private Button DeleteButton;
	@FXML
	private Button FileButton;
	@FXML
	private TableView <Dog>TableGrid;
	@FXML
	private TableColumn<Dog, String> c1;
	@FXML
	private TableColumn<Dog, String> c2;
	@FXML
	private TableColumn<Dog, String> c3;
	@FXML
	private TableColumn<Dog, String> c4;
	@FXML
	private TableColumn<Dog, String> c5;
	@FXML
	private TextField c1Text;
	@FXML
	private TextField c2Text;
	@FXML
	private TextField c3Text;
	@FXML
	private TextField c4Text;
	@FXML
	private TextField c5Text;
	@FXML
	private Button AddButton;

	// Event Listener on Button[#DeleteButton].onAction
	@FXML
	public void Delete(ActionEvent event) {
		// TODO Autogenerated
		Dog dog=TableGrid.getSelectionModel().getSelectedItem();
		DB.dog.remove(dog);
	}
	

	// Event Listener on Button[#FileButton].onAction
	@FXML
	public void File(ActionEvent event) {
		// TODO Autogenerated

		int d = DB.dog.size();
		
		try {
			File file = new File("dogFile.txt");

			if(!file.exists())
			file.createNewFile();

			PrintWriter pw = new PrintWriter(file);
			for(int j=0;j<d;j++) {
				Dog dog1 = DB.dog.get(j);
				pw.println("ÑÎÁÀÊÀ ÍÎÌÅÐ "+(j+1));
				pw.println(dog1.Name);
				pw.println(dog1.Breed);
				pw.println(dog1.Age);
				pw.println(dog1.Owner);
				pw.println(dog1.Price);
			}

			pw.close();

			BufferedReader br = new BufferedReader(new FileReader("dogFile.txt"));
			String line;
			while((line=br.readLine())!=null) {
			System.out.println(line);
			}
			br.close();
			}
			catch(IOException e) {
			System.out.println("Error"+e);
			}
	}
	
	
	// Event Listener on Button[#AddButton].onAction
	@FXML
	public void Add(ActionEvent event) {
		// TODO Autogenerated
		DB.dog.add(new Dog(c1Text.getText(),c2Text.getText(),Integer.parseInt(c3Text.getText()),c4Text.getText(),Integer.parseInt(c5Text.getText())));
	}
	
	@FXML
	void initialize() {

    	c1.setCellValueFactory(new PropertyValueFactory<>("name"));
    	c2.setCellValueFactory(new PropertyValueFactory<>("breed"));
    	c3.setCellValueFactory(new PropertyValueFactory<>("age"));
    	c4.setCellValueFactory(new PropertyValueFactory<>("owner"));
    	c5.setCellValueFactory(new PropertyValueFactory<>("price"));
    	TableGrid.setItems(DB.dog);
   }
	
}
